keyboard.send_keys("<tab><tab>")
keyboard.send_keys(" ")
keyboard.send_keys("<tab><tab>")

keyboard.send_keys("1")
keyboard.send_keys("<tab>")
keyboard.send_keys("w")
keyboard.send_keys("<tab>")
keyboard.send_keys("1")
keyboard.send_keys("<tab>")
keyboard.send_keys("<tab>")
keyboard.send_keys("<tab>")
keyboard.send_keys(" ")
keyboard.send_keys("<tab>")
keyboard.send_keys(" ")
keyboard.send_keys("<tab>")
keyboard.send_keys(" ")
keyboard.send_keys("<tab>")
keyboard.send_keys(" ")
keyboard.send_keys("<tab>")
keyboard.send_keys(" ")
keyboard.send_keys("<tab>")
keyboard.send_keys(" ")
keyboard.send_keys("<tab><tab>")
keyboard.send_keys(" ")