keyboard.send_keys("<tab>")
keyboard.send_keys("<down>")
keyboard.send_keys("<tab>")
keyboard.send_keys("adminEp")
keyboard.send_keys("<tab>")
keyboard.send_keys("Geoiws")
keyboard.send_keys("<tab>")
keyboard.send_keys("Geoiws")
keyboard.send_keys("<tab>")
keyboard.send_keys(" ")